### ISSUE TITLE
good job!!

### ISSUE THREAD

**Issue by halaassaly** [WebAhead7/Get-It-Done#12]
We like the design! it is pretty awsome and cool!!
we would recomend you using the break-word feacure in css so that if somone writes a long task, the line would break automaticly and will prevent it from overflowing outside the container.

great job overall!! 👍

**Comment by rakad-kh** [comment]
Thank you so much, actually there is no overflowing outside the container, you can try it yourself .
![Uploading Screen Shot 2020-10-28 at 11.12.55.png…]()
