### ISSUE TITLE
extra css files?

### ISSUE THREAD

**Issue by mjmajadly** [WebAhead7/Get-It-Done#13]
I see all.css and all.min.css in the directory but not linked in the html. Are these used somewhere?

**Comment by rakad-kh** [comment]
yeah they are :)

**Comment by Karyum** [comment]
no they are not

**Comment by rakad-kh** [comment]
fixed.
thanks you bro for updating us.

**Comment by Karyum** [comment]
doesn't look like it was fixed

**Comment by rakad-kh** [comment]
made a push, thanks Mario for updating us
