### ISSUE TITLE
live site is not displaying things correctly

### ISSUE THREAD

**Issue by mjmajadly** [WebAhead7/Get-It-Done#8]
no background, style, css, anything showing in the live site "https://webahead7.github.io/Get-It-Done/"

**Comment by muhkham** [comment]
mario said leave it for now :D

**Comment by rakad-kh** [comment]
Clone it for now..

**Comment by mjmajadly** [comment]
try switching the css links in the HTML file

**Comment by shiryz** [comment]
The issue is because you don't have relative paths to your files from your HTML
as in `/src/index.css` instead of `./src/index.css`

**Comment by rakad-kh** [comment]
fixed, thanks Shireen for the fix, and thank you Majadly for the noticing:)
