### ISSUE TITLE
your app is not secure

### ISSUE THREAD

**Issue by Ammaryus** [WebAhead7/Get-It-Done#9]
try to insert this to-do text: <img src="h.png" onerror="alert('Hello World!')"/>
over all good job :+1:

**Comment by Ammaryus** [comment]
i mean this text "<img src="hello.png" onerror="alert('Hello World')"/>"

**Comment by Ammaryus** [comment]
I mean this text: `<img src="hello.png" onerror="alert('Hello World!')'/>`

**Comment by ahmad420** [comment]
can you give us more explanation?

**Comment by rakad-kh** [comment]
fixed now, thanks for the deep analysis bro
